name: Test deployed with '/run tests' comment

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened 
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: IgorTodorovskiIBM/meta/.github/workflows/build_and_test.yml@main
    with:
      repo: 'https://github.com/ZOSOpenTools/metaport.git'
      use_branch_as_build_branch: true
    secrets: inherit
