name: Test deployed with '/run tests' comment

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened 
  workflow_dispatch:

jobs:
  trigger-jenkins-job:
    steps:
        uses: IgorTodorovskiIBM/meta/build_and_test@main
        with:
          repo: 'https://github.com/ZOSOpenTools/metaport.git'
