name: Test deployed with '/run tests' comment

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened 
  workflow_dispatch:

jobs:
  trigger-jenkins-job:
    if: github.event.issue.pull_request || contains(github.event.comment.body, '/run tests') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    launchit:
      uses: IgorTodorovskiIBM/meta/.github/workflows/build_and_test.yml@main
      secrets: inherit
      with:
        repo: 'https://github.com/ZOSOpenTools/metaport.git'
