name: shellcheck

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.sh'
  push:
    branches:
      - main
    paths:
      - '**.sh'

jobs:
  shellcheck-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint check
        uses: azohra/shell-linter@v0.6.0
